# Generated by Django 5.1.7 on 2025-03-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specialization", models.CharField(max_length=100)),
                (
                    "assigned_classes",
                    models.ManyToManyField(
                        related_name="assigned_teachers", to="schedules.class"
                    ),
                ),
            ],
        ),
    ]
