# Generated by Django 5.1.7 on 2025-03-23 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="schedule",
            old_name="time",
            new_name="end_time",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="class_group",
        ),
        migrations.AddField(
            model_name="schedule",
            name="start_time",
            field=models.TimeField(default="00:00:00"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="schedule",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="teacher",
            field=models.ForeignKey(
                limit_choices_to={"role": "teacher"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="classroom",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="schedules.classroom",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "students",
                    models.ManyToManyField(
                        limit_choices_to={"role": "student"},
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="schedule",
            name="group",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="schedules.group",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="schedule",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="schedules.subject"
            ),
        ),
    ]
